### ISSUE TITLE
DrangonBones json format support

### ISSUE THREAD

**Issue by ghost** [UlyssesWu/D2Evil#2]
Just found your repo from 

https://github.com/DragonBones/Tools/issues/19

Is it possible to convert a .moc3 file to a json format like the one for DrangonBones? It will be very helpful for the community as a open source alternative to live2d.

**Comment by UlyssesWu** [comment]
DragonBones Tools `convert Live2D to DragonBones` feature only seems to work for moc models (from Cubism 2), not moc3 files (Cubism 3+).
Although I already convert moc and moc3 files to JSON for edit and analysis, I have no motivation to add support for DragonBones. I don't use DragonBones, so I'm not sure if DragonBones supports all features in Cubism 4.

The developer for DragonBones has done a good job for parsing moc format, I think he may also be able to achieve what you want.

**Comment by ghost** [comment]
Thanks for providing insights about the DragonBones.
Will you consider releasing the code (or maybe a binary) for parsing moc3 files into JSON files? That would be very helpful for research and analysis purpose.

**Comment by UlyssesWu** [comment]
It used to be public, but has been removed and there is no further plan for release. Read other issues to understand the reason.
